language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - git checkout master
  - composer self-update && composer install

script: bin/kahlan --coverage=3 --coverage-scrutinizer="export.xml"

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover "export.xml"